name = "healthpulse-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Environment variables for Supabase
[vars]
SUPABASE_URL = "https://xchwpafqmkfheyxuvtij.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjaHdwYWZxbWtmaGV5eHV2dGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTc1ODgsImV4cCI6MjA2NzA5MzU4OH0.64Ool-fY2NGDgyhyBW6uNdHI7pucVOmtJMRS0uRqitc"

[env.production]
name = "healthpulse-api"

[env.staging]
name = "healthpulse-api-staging"

[build]
command = "echo 'No build step needed for Workers'"

# Custom domain configuration
[[env.production.routes]]
pattern = "api.pulse.health-sathi.org/*"
zone_name = "health-sathi.org"

[[env.staging.routes]]
pattern = "api-staging.pulse.health-sathi.org/*"
zone_name = "health-sathi.org"