name = "healthpulse-api"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Environment variables for Supabase
[vars]
SUPABASE_URL = "https://xchwpafqmkfheyxuvtij.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJI"

[[kv_namespaces]]
binding = "MESSAGES_KV"
id = "f82b8dd460634dda8f694d91b39ba3d3"



[env.production]
name = "healthpulse-api"

[env.staging]
name = "healthpulse-api-staging"

[build]
command = "echo 'No build step needed for Workers'"

# Custom domain configuration
[[env.production.routes]]
pattern = "api.pulse.health-sathi.org/*"
zone_name = "health-sathi.org"

[[env.staging.routes]]
pattern = "api-staging.pulse.health-sathi.org/*"
zone_name = "health-sathi.org"